version: '3.2'
services:

  web:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    container_name: web
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
      - API_URL=http://localhost:8000/api

  api:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: api
    environment:
      - APP_NAME=FDesk
      - APP_ENV=local
      - APP_KEY=base64:CPDFIOVtkMTW4s9kLQYVrNNCbA7U0HtTcYb/I84eKjU=
      - APP_DEBUG=true
      - APP_URL=http://localhost

      - LOG_CHANNEL=stack

      - DB_CONNECTION=sqlite
      - DB_FOREIGN_KEYS=true

      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=null
      - MAIL_FROM_NAME="${APP_NAME}"

      - OPCACHE_REVALIDATE_FREQ=0
      - OPCACHE_VALIDATE_TIMESTAMPS=On

      - ACCESS_CONTROL_ALLOW_ORIGIN="http://localhost"

    ports:
      - "8000:80"
    restart: always